services:
  - type: web
    name: blutsgeschwister-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    plan: free
